---
- name: set vars
  set_fact:
    docker_image: '{{ app_prometheus_docker_image }}'
    docker_container: '{{ app_prometheus_docker_container }}'
    docker_volume_config: '{{ app_prometheus_docker_volume_config }}'
    docker_volume_data: '{{ app_prometheus_docker_volume_data }}'
    docker_network: '{{ app_prometheus_docker_network }}'
    tmp_dir: '{{ app_prometheus_tmp_dir }}'

- name: Ensure image is pulled
  community.docker.docker_image:
    name: "{{ docker_image }}"
    source: pull
    force_source: yes
  register: pulled

- name: Remove container
  community.docker.docker_container:
    name: "{{ docker_container }}"
    state: absent
  when: pulled.changed

- name: Get infos on container
  community.docker.docker_container_info:
    name: "{{ docker_container }}"
  register: result

- name: Create config volume
  community.docker.docker_volume:
    name: "{{ docker_volume_config }}"

- name: Create data volume
  community.docker.docker_volume:
    name: "{{ docker_volume_data }}"

- name: Create network
  community.docker.docker_network:
    name: "{{ docker_network }}"
    driver_options:
          com.docker.network.bridge.name: "br-{{ docker_network }}"

- name: Create prometheus container
  community.docker.docker_container:
    image: "{{ docker_image }}"
    mounts:
     - source: "{{ docker_volume_config }}"
       target: /etc/prometheus
     - source: "{{ docker_volume_data }}"
       target: /prometheus
    name: "{{ docker_container }}"
    command: --web.config.file=/etc/prometheus/web-config.yml --config.file=/etc/prometheus/prometheus.yml
    networks:
     - name: "{{ docker_network }}"
    restart_policy: unless-stopped
    state: started
  when:
    pulled.changed
    or
    result.exists == false

- name: Create tmp directory
  ansible.builtin.file:
    path: "{{ tmp_dir }}"
    state: directory
  when:
    result.exists == false

- name: Copy prometheus files
  ansible.builtin.template:
    src: "{{ item }}.yml.j2"
    dest: "{{ tmp_dir }}/{{ item }}.yml"
  with_items:
    - "prometheus"
    - "web-config"
  when:
    result.exists == false

- name: Copy config files into prometheus container
  shell: "docker cp {{ app_prometheus_tmp_dir }}/. {{ docker_container }}:/etc/prometheus"
  when:
    result.exists == false

- name: Remove tmp directory
  ansible.builtin.file:
    path: "{{ tmp_dir }}"
    state: absent
  when:
    result.exists == false

- name: Restart container
  community.docker.docker_container:
    name: "{{ docker_container }}"
    restart: yes
  when:
    result.exists == false
